namespace Blaze2SDK.Blaze.Authentication;

public enum NucleusCode : int
{
    UNKNOWN = 0,
    VALIDATION_FAILED = 1,
    NO_SUCH_USER = 2,
    NO_SUCH_COUNTRY = 3,
    NO_SUCH_PERSONA = 4,
    NO_SUCH_EXTERNAL_REFERENCE = 5,
    NO_SUCH_NAMESPACE = 6,
    INVALID_PASSWORD = 7,
    CODE_ALREADY_USED = 8,
    INVALID_CODE = 9,
    PARSE_EXCEPTION = 10,
    NO_SUCH_GROUP = 11,
    NO_SUCH_GROUP_NAME = 12,
    NO_ASSOCIATED_PRODUCT = 13,
    CODE_ALREADY_DISABLED = 14,
    GROUP_NAME_DOES_NOT_MATCH = 15,
}

