namespace Blaze2SDK.Blaze.Clubs;

public enum ClubOnlineStatusUpdateReason : int
{
    CLUBS_USER_SESSION_CREATED = 0,
    CLUBS_USER_SESSION_DESTROYED = 1,
    CLUBS_USER_JOINED_CLUB = 2,
    CLUBS_USER_LEFT_CLUB = 3,
    CLUBS_USER_ONLINE_STATUS_UPDATED = 4,
    CLUBS_CLUB_DESTROYED = 5,
    CLUBS_CLUB_CREATED = 6,
    CLUBS_CLUB_SETTINGS_UPDATED = 7,
    CLUBS_USER_PROMOTED_TO_GM = 8,
}

