using Blaze3SDK.Blaze;
using Blaze3SDK.Blaze.GameManager;
using BlazeCommon;
using static Blaze3SDK.Components.GameManager;

namespace Blaze3SDK.Components
{
    public class GameManager : ComponentData<GameManagerCommand, GameManagerNotification, GameManagerError>
    {
        public GameManager() : base((ushort)Component.GameManager)
        {

        }

        public override Type GetCommandErrorResponseType(GameManagerCommand command) => command switch
        {
            GameManagerCommand.createGame => throw new NotImplementedException(),
            GameManagerCommand.destroyGame => throw new NotImplementedException(),
            GameManagerCommand.advanceGameState => throw new NotImplementedException(),
            GameManagerCommand.setGameSettings => throw new NotImplementedException(),
            GameManagerCommand.setPlayerCapacity => throw new NotImplementedException(),
            GameManagerCommand.setPresenceMode => throw new NotImplementedException(),
            GameManagerCommand.setGameAttributes => throw new NotImplementedException(),
            GameManagerCommand.setPlayerAttributes => throw new NotImplementedException(),
            GameManagerCommand.joinGame => throw new NotImplementedException(),
            GameManagerCommand.removePlayer => throw new NotImplementedException(),
            GameManagerCommand.startMatchmaking => throw new NotImplementedException(),
            GameManagerCommand.cancelMatchmaking => throw new NotImplementedException(),
            GameManagerCommand.finalizeGameCreation => throw new NotImplementedException(),
            GameManagerCommand.listGames => throw new NotImplementedException(),
            GameManagerCommand.setPlayerCustomData => throw new NotImplementedException(),
            GameManagerCommand.replayGame => throw new NotImplementedException(),
            GameManagerCommand.returnDedicatedServerToPool => throw new NotImplementedException(),
            GameManagerCommand.joinGameByGroup => throw new NotImplementedException(),
            GameManagerCommand.leaveGameByGroup => throw new NotImplementedException(),
            GameManagerCommand.migrateGame => throw new NotImplementedException(),
            GameManagerCommand.updateGameHostMigrationStatus => throw new NotImplementedException(),
            GameManagerCommand.resetDedicatedServer => throw new NotImplementedException(),
            GameManagerCommand.updateGameSession => throw new NotImplementedException(),
            GameManagerCommand.banPlayer => throw new NotImplementedException(),
            GameManagerCommand.updateMeshConnection => throw new NotImplementedException(),
            GameManagerCommand.removePlayerFromBannedList => throw new NotImplementedException(),
            GameManagerCommand.clearBannedList => throw new NotImplementedException(),
            GameManagerCommand.getBannedList => throw new NotImplementedException(),
            GameManagerCommand.addQueuedPlayerToGame => throw new NotImplementedException(),
            GameManagerCommand.updateGameName => throw new NotImplementedException(),
            GameManagerCommand.ejectHost => throw new NotImplementedException(),
            GameManagerCommand.getGameListSnapshot => throw new NotImplementedException(),
            GameManagerCommand.getGameListSubscription => throw new NotImplementedException(),
            GameManagerCommand.destroyGameList => throw new NotImplementedException(),
            GameManagerCommand.getFullGameData => throw new NotImplementedException(),
            GameManagerCommand.getMatchmakingConfig => throw new NotImplementedException(),
            GameManagerCommand.getGameDataFromId => throw new NotImplementedException(),
            GameManagerCommand.addAdminPlayer => throw new NotImplementedException(),
            GameManagerCommand.removeAdminPlayer => throw new NotImplementedException(),
            GameManagerCommand.setPlayerTeam => throw new NotImplementedException(),
            GameManagerCommand.changeGameTeamId => throw new NotImplementedException(),
            GameManagerCommand.migrateAdminPlayer => throw new NotImplementedException(),
            GameManagerCommand.getUserSetGameListSubscription => throw new NotImplementedException(),
            GameManagerCommand.swapPlayersTeam => throw new NotImplementedException(),
            GameManagerCommand.registerDynamicDedicatedServerCreator => throw new NotImplementedException(),
            GameManagerCommand.unregisterDynamicDedicatedServerCreator => throw new NotImplementedException(),
            _ => typeof(NullStruct)
        };

        public override Type GetCommandRequestType(GameManagerCommand command) => command switch
        {
            GameManagerCommand.createGame => typeof(CreateGameRequest),
            GameManagerCommand.destroyGame => typeof(DestroyGameRequest),
            GameManagerCommand.advanceGameState => typeof(AdvanceGameStateRequest),
            GameManagerCommand.setGameSettings => typeof(SetGameSettingsRequest),
            GameManagerCommand.setPlayerCapacity => typeof(SetPlayerCapacityRequest),
            GameManagerCommand.setPresenceMode => typeof(SetPresenceModeRequest),
            GameManagerCommand.setGameAttributes => typeof(SetGameAttributesRequest),
            GameManagerCommand.setPlayerAttributes => typeof(SetPlayerAttributesRequest),
            GameManagerCommand.joinGame => typeof(JoinGameRequest),
            GameManagerCommand.removePlayer => typeof(RemovePlayerRequest),
            GameManagerCommand.startMatchmaking => typeof(StartMatchmakingRequest),
            GameManagerCommand.cancelMatchmaking => typeof(CancelMatchmakingRequest),
            GameManagerCommand.finalizeGameCreation => typeof(UpdateGameSessionRequest),
            GameManagerCommand.listGames => throw new NotImplementedException(),
            GameManagerCommand.setPlayerCustomData => typeof(SetPlayerCustomDataRequest),
            GameManagerCommand.replayGame => typeof(ReplayGameRequest),
            GameManagerCommand.returnDedicatedServerToPool => typeof(ReturnDedicatedServerToPoolRequest),
            GameManagerCommand.joinGameByGroup => throw new NotImplementedException(),
            GameManagerCommand.leaveGameByGroup => throw new NotImplementedException(),
            GameManagerCommand.migrateGame => throw new NotImplementedException(),
            GameManagerCommand.updateGameHostMigrationStatus => typeof(UpdateGameHostMigrationStatusRequest),
            GameManagerCommand.resetDedicatedServer => throw new NotImplementedException(),
            GameManagerCommand.updateGameSession => typeof(UpdateGameSessionRequest),
            GameManagerCommand.banPlayer => typeof(BanPlayerRequest),
            GameManagerCommand.updateMeshConnection => typeof(UpdateMeshConnectionRequest),
            GameManagerCommand.removePlayerFromBannedList => typeof(RemovePlayerFromBannedListRequest),
            GameManagerCommand.clearBannedList => throw new NotImplementedException(),
            GameManagerCommand.getBannedList => typeof(BannedListRequest),
            GameManagerCommand.addQueuedPlayerToGame => typeof(AddQueuedPlayerToGameRequest),
            GameManagerCommand.updateGameName => typeof(UpdateGameNameRequest),
            GameManagerCommand.ejectHost => typeof(EjectHostRequest),
            GameManagerCommand.getGameListSnapshot => typeof(GetGameListRequest),
            GameManagerCommand.getGameListSubscription => throw new NotImplementedException(),
            GameManagerCommand.destroyGameList => typeof(DestroyGameListRequest),
            GameManagerCommand.getFullGameData => typeof(GetFullGameDataRequest),
            GameManagerCommand.getMatchmakingConfig => throw new NotImplementedException(),
            GameManagerCommand.getGameDataFromId => typeof(GetGameDataFromIdRequest),
            GameManagerCommand.addAdminPlayer => throw new NotImplementedException(),
            GameManagerCommand.removeAdminPlayer => throw new NotImplementedException(),
            GameManagerCommand.setPlayerTeam => typeof(SetPlayerTeamRequest),
            GameManagerCommand.changeGameTeamId => typeof(ChangeTeamIdRequest),
            GameManagerCommand.migrateAdminPlayer => throw new NotImplementedException(),
            GameManagerCommand.getUserSetGameListSubscription => typeof(GetUserSetGameListSubscriptionRequest),
            GameManagerCommand.swapPlayersTeam => typeof(SwapPlayersTeamRequest),
            GameManagerCommand.registerDynamicDedicatedServerCreator => typeof(RegisterDynamicDedicatedServerCreatorRequest),
            GameManagerCommand.unregisterDynamicDedicatedServerCreator => typeof(UnregisterDynamicDedicatedServerCreatorRequest),
            _ => typeof(NullStruct)
        };


        public override Type GetCommandResponseType(GameManagerCommand command) => command switch
        {
            GameManagerCommand.createGame => typeof(CreateGameResponse),
            GameManagerCommand.destroyGame => typeof(DestroyGameResponse),
            GameManagerCommand.advanceGameState => typeof(NullStruct),
            GameManagerCommand.setGameSettings => typeof(NullStruct),
            GameManagerCommand.setPlayerCapacity => typeof(NullStruct),
            GameManagerCommand.setPresenceMode => typeof(NullStruct),
            GameManagerCommand.setGameAttributes => typeof(NullStruct),
            GameManagerCommand.setPlayerAttributes => typeof(NullStruct),
            GameManagerCommand.joinGame => typeof(JoinGameResponse),
            GameManagerCommand.removePlayer => throw new NotImplementedException(),
            GameManagerCommand.startMatchmaking => typeof(StartMatchmakingResponse),
            GameManagerCommand.cancelMatchmaking => throw new NotImplementedException(),
            GameManagerCommand.finalizeGameCreation => typeof(NullStruct),
            GameManagerCommand.listGames => typeof(ListGamesResponse),
            GameManagerCommand.setPlayerCustomData => typeof(NullStruct),
            GameManagerCommand.replayGame => throw new NotImplementedException(),
            GameManagerCommand.returnDedicatedServerToPool => throw new NotImplementedException(),
            GameManagerCommand.joinGameByGroup => throw new NotImplementedException(),
            GameManagerCommand.leaveGameByGroup => throw new NotImplementedException(),
            GameManagerCommand.migrateGame => throw new NotImplementedException(),
            GameManagerCommand.updateGameHostMigrationStatus => throw new NotImplementedException(),
            GameManagerCommand.resetDedicatedServer => throw new NotImplementedException(),
            GameManagerCommand.updateGameSession => typeof(NullStruct),
            GameManagerCommand.banPlayer => throw new NotImplementedException(),
            GameManagerCommand.updateMeshConnection => typeof(NullStruct),
            GameManagerCommand.removePlayerFromBannedList => throw new NotImplementedException(),
            GameManagerCommand.clearBannedList => throw new NotImplementedException(),
            GameManagerCommand.getBannedList => typeof(BannedListResponse),
            GameManagerCommand.addQueuedPlayerToGame => throw new NotImplementedException(),
            GameManagerCommand.updateGameName => throw new NotImplementedException(),
            GameManagerCommand.ejectHost => throw new NotImplementedException(),
            GameManagerCommand.getGameListSnapshot => typeof(GetGameListResponse),
            GameManagerCommand.getGameListSubscription => throw new NotImplementedException(),
            GameManagerCommand.destroyGameList => throw new NotImplementedException(),
            GameManagerCommand.getFullGameData => typeof(GetFullGameDataResponse),
            GameManagerCommand.getMatchmakingConfig => typeof(GetMatchmakingConfigResponse),
            GameManagerCommand.getGameDataFromId => throw new NotImplementedException(),
            GameManagerCommand.addAdminPlayer => throw new NotImplementedException(),
            GameManagerCommand.removeAdminPlayer => throw new NotImplementedException(),
            GameManagerCommand.setPlayerTeam => throw new NotImplementedException(),
            GameManagerCommand.changeGameTeamId => throw new NotImplementedException(),
            GameManagerCommand.migrateAdminPlayer => throw new NotImplementedException(),
            GameManagerCommand.getUserSetGameListSubscription => throw new NotImplementedException(),
            GameManagerCommand.swapPlayersTeam => throw new NotImplementedException(),
            GameManagerCommand.registerDynamicDedicatedServerCreator => typeof(RegisterDynamicDedicatedServerCreatorResponse),
            GameManagerCommand.unregisterDynamicDedicatedServerCreator => typeof(UnregisterDynamicDedicatedServerCreatorResponse),
            _ => typeof(NullStruct)
        };

        public override Type GetNotificationType(GameManagerNotification notification) => notification switch
        {
            GameManagerNotification.NotifyMatchmakingFailed => typeof(NotifyMatchmakingFailed),
            GameManagerNotification.NotifyMatchmakingAsyncStatus => typeof(NotifyMatchmakingAsyncStatus),
            GameManagerNotification.NotifyGameCreated => typeof(NotifyGameCreated),
            GameManagerNotification.NotifyGameRemoved => typeof(NotifyGameRemoved),
            GameManagerNotification.NotifyGameSetup => typeof(NotifyGameSetup),
            GameManagerNotification.NotifyPlayerJoining => typeof(NotifyPlayerJoining),
            GameManagerNotification.NotifyJoiningPlayerInitiateConnections => typeof(NotifyGameSetup),
            GameManagerNotification.NotifyPlayerJoiningQueue => typeof(NotifyPlayerJoining),
            GameManagerNotification.NotifyPlayerPromotedFromQueue => typeof(NotifyPlayerJoining),
            GameManagerNotification.NotifyPlayerClaimingReservation => typeof(NotifyPlayerJoining),
            GameManagerNotification.NotifyPlayerJoinCompleted => typeof(NotifyPlayerJoinCompleted),
            GameManagerNotification.NotifyPlayerRemoved => typeof(NotifyPlayerRemoved),
            GameManagerNotification.NotifyHostMigrationFinished => typeof(NotifyHostMigrationFinished),
            GameManagerNotification.NotifyHostMigrationStart => typeof(NotifyHostMigrationStart),
            GameManagerNotification.NotifyPlatformHostInitialized => typeof(NotifyPlatformHostInitialized),
            GameManagerNotification.NotifyGameAttribChange => typeof(NotifyGameAttribChange),
            GameManagerNotification.NotifyPlayerAttribChange => typeof(NotifyPlayerAttribChange),
            GameManagerNotification.NotifyPlayerCustomDataChange => typeof(NotifyPlayerCustomDataChange),
            GameManagerNotification.NotifyGameStateChange => typeof(NotifyGameStateChange),
            GameManagerNotification.NotifyGameSettingsChange => typeof(NotifyGameSettingsChange),
            GameManagerNotification.NotifyGameCapacityChange => typeof(NotifyGameCapacityChange),
            GameManagerNotification.NotifyGameReset => typeof(NotifyGameReset),
            GameManagerNotification.NotifyGameReportingIdChange => typeof(NotifyGameReportingIdChange),
            GameManagerNotification.NotifyGameSessionUpdated => typeof(GameSessionUpdatedNotification),
            GameManagerNotification.NotifyGamePlayerStateChange => typeof(NotifyGamePlayerStateChange),
            GameManagerNotification.NotifyGamePlayerTeamChange => typeof(NotifyGamePlayerTeamChange),
            GameManagerNotification.NotifyGameTeamIdChange => typeof(NotifyGameTeamIdChange),
            GameManagerNotification.NotifyProcessQueue => typeof(NotifyProcessQueue),
            GameManagerNotification.NotifyPresenceModeChanged => typeof(NotifyPresenceModeChanged),
            GameManagerNotification.NotifyGamePlayerQueuePositionChange => typeof(NotifyGamePlayerQueuePositionChange),
            GameManagerNotification.NotifyGameListUpdate => typeof(NotifyGameListUpdate),
            GameManagerNotification.NotifyAdminListChange => typeof(NotifyAdminListChange),
            GameManagerNotification.NotifyCreateDynamicDedicatedServerGame => typeof(NotifyCreateDynamicDedicatedServerGame),
            GameManagerNotification.NotifyGameNameChange => typeof(NotifyGameNameChange),
            _ => typeof(NullStruct)
        };

        public enum GameManagerCommand : ushort
        {
            createGame = 1,
            destroyGame = 2,
            advanceGameState = 3,
            setGameSettings = 4,
            setPlayerCapacity = 5,
            setPresenceMode = 6,
            setGameAttributes = 7,
            setPlayerAttributes = 8,
            joinGame = 9,
            removePlayer = 11,
            startMatchmaking = 13,
            cancelMatchmaking = 14,
            finalizeGameCreation = 15,
            listGames = 17,
            setPlayerCustomData = 18,
            replayGame = 19,
            returnDedicatedServerToPool = 20,
            joinGameByGroup = 21,
            leaveGameByGroup = 22,
            migrateGame = 23,
            updateGameHostMigrationStatus = 24,
            resetDedicatedServer = 25,
            updateGameSession = 26,
            banPlayer = 27,
            updateMeshConnection = 29,
            removePlayerFromBannedList = 31,
            clearBannedList = 32,
            getBannedList = 33,
            addQueuedPlayerToGame = 38,
            updateGameName = 39,
            ejectHost = 40,
            getGameListSnapshot = 100,
            getGameListSubscription = 101,
            destroyGameList = 102,
            getFullGameData = 103,
            getMatchmakingConfig = 104,
            getGameDataFromId = 105,
            addAdminPlayer = 106,
            removeAdminPlayer = 107,
            setPlayerTeam = 108,
            changeGameTeamId = 109,
            migrateAdminPlayer = 110,
            getUserSetGameListSubscription = 111,
            swapPlayersTeam = 112,
            registerDynamicDedicatedServerCreator = 150,
            unregisterDynamicDedicatedServerCreator = 151
        }

        public enum GameManagerNotification : ushort
        {
            NotifyMatchmakingFailed = 10,
            NotifyMatchmakingAsyncStatus = 12,
            NotifyGameCreated = 15,
            NotifyGameRemoved = 16,
            NotifyGameSetup = 20,
            NotifyPlayerJoining = 21,
            NotifyJoiningPlayerInitiateConnections = 22,
            NotifyPlayerJoiningQueue = 23,
            NotifyPlayerPromotedFromQueue = 24,
            NotifyPlayerClaimingReservation = 25,
            NotifyPlayerJoinCompleted = 30,
            NotifyPlayerRemoved = 40,
            NotifyHostMigrationFinished = 60,
            NotifyHostMigrationStart = 70,
            NotifyPlatformHostInitialized = 71,
            NotifyGameAttribChange = 80,
            NotifyPlayerAttribChange = 90,
            NotifyPlayerCustomDataChange = 95,
            NotifyGameStateChange = 100,
            NotifyGameSettingsChange = 110,
            NotifyGameCapacityChange = 111,
            NotifyGameReset = 112,
            NotifyGameReportingIdChange = 113,
            NotifyGameSessionUpdated = 115,
            NotifyGamePlayerStateChange = 116,
            NotifyGamePlayerTeamChange = 117,
            NotifyGameTeamIdChange = 118,
            NotifyProcessQueue = 119,
            NotifyPresenceModeChanged = 120,
            NotifyGamePlayerQueuePositionChange = 121,
            NotifyGameListUpdate = 201,
            NotifyAdminListChange = 202,
            NotifyCreateDynamicDedicatedServerGame = 220,
            NotifyGameNameChange = 230
        }

        public enum GameManagerError
        {
            GAMEMANAGER_ERR_INVALID_GAME_SETTINGS = 65540,
            GAMEMANAGER_ERR_INVALID_GAME_ID = 131076,
            GAMEMANAGER_ERR_JOIN_METHOD_NOT_SUPPORTED = 196612,
            GAMEMANAGER_ERR_GAME_FULL = 262148,
            GAMEMANAGER_ERR_INVALID_GAME_STATE_TRANSITION = 327684,
            GAMEMANAGER_ERR_INVALID_GAME_STATE_ACTION = 393220,
            GAMEMANAGER_ERR_FAILED_IN_GAME_DESTROY = 458756,
            GAMEMANAGER_ERR_QUEUE_FULL = 524292,
            GAMEMANAGER_ERR_INVALID_GAME_ENTRY_CRITERIA = 589828,
            GAMEMANAGER_ERR_GAME_PROTOCOL_VERSION_MISMATCH = 655364,
            GAMEMANAGER_ERR_GAME_IN_PROGRESS = 720900,
            GAMEMANAGER_ERR_RESERVED_GAME_ID_INVALID = 786436,
            GAMEMANAGER_ERR_INVALID_JOIN_METHOD = 851972,
            GAMEMANAGER_ERR_SLOT_OCCUPIED = 917508,
            GAMEMANAGER_ERR_NOT_VIRTUAL_GAME = 983044,
            GAMEMANAGER_ERR_NOT_TOPOLOGY_HOST = 1048580,
            GAMEMANAGER_ERR_PERMISSION_DENIED = 1966084,
            GAMEMANAGER_ERR_ALREADY_ADMIN = 2031620,
            GAMEMANAGER_ERR_NOT_IN_ADMIN_LIST = 2097156,
            GAMEMANAGER_ERR_DEDICATED_SERVER_HOST = 2162692,
            GAMEMANAGER_ERR_INVALID_QUEUE_METHOD = 3276804,
            GAMEMANAGER_ERR_PLAYER_NOT_IN_QUEUE = 3342340,
            GAMEMANAGER_ERR_DEQUEUE_WHILE_MIGRATING = 3407876,
            GAMEMANAGER_ERR_DEQUEUE_WHILE_IN_PROGRESS = 3473412,
            GAMEMANAGER_ERR_PLAYER_NOT_FOUND = 6619140,
            GAMEMANAGER_ERR_ALREADY_GAME_MEMBER = 6750212,
            GAMEMANAGER_ERR_REMOVE_PLAYER_FAILED = 6815748,
            GAMEMANAGER_ERR_INVALID_PLAYER_PASSEDIN = 7012356,
            GAMEMANAGER_ERR_JOIN_PLAYER_FAILED = 7077892,
            GAMEMANAGER_ERR_PLAYER_BANNED = 7208964,
            GAMEMANAGER_ERR_GAME_ENTRY_CRITERIA_FAILED = 7274500,
            GAMEMANAGER_ERR_ALREADY_IN_QUEUE = 7340036,
            GAMEMANAGER_ERR_ENFORCING_SINGLE_GROUP_JOINS = 7405572,
            GAMEMANAGER_ERR_BANNED_PLAYER_NOT_FOUND = 7471108,
            GAMEMANAGER_ERR_BANNED_LIST_MAX = 7536644,
            GAMEMANAGER_ERR_RESERVATION_ALREADY_EXISTS = 7864324,
            GAMEMANAGER_ERR_NO_RESERVATION_FOUND = 7929860,
            GAMEMANAGER_ERR_INVALID_GAME_ENTRY_TYPE = 7995396,
            GAMEMANAGER_ERR_INVALID_GROUP_ID = 9895940,
            GAMEMANAGER_ERR_PLAYER_NOT_IN_GROUP = 9961476,
            GAMEMANAGER_ERR_INVALID_MATCHMAKING_CRITERIA = 13107204,
            GAMEMANAGER_ERR_UNKNOWN_MATCHMAKING_SESSION_ID = 13172740,
            GAMEMANAGER_ERR_NOT_MATCHMAKING_SESSION_OWNER = 13238276,
            GAMEMANAGER_ERR_MATCHMAKING_NO_JOINABLE_GAMES = 13303812,
            GAMEMANAGER_ERR_MATCHMAKING_USERSESSION_NOT_FOUND = 13434884,
            GAMEMANAGER_ERR_MATCHMAKING_EXCEEDED_MAX_REQUESTS = 13500420,
            GAMEMANAGER_ERR_PLAYER_CAPACITY_TOO_SMALL = 15073284,
            GAMEMANAGER_ERR_PLAYER_CAPACITY_TOO_LARGE = 15138820,
            GAMEMANAGER_ERR_PLAYER_CAPACITY_IS_ZERO = 15204356,
            GAMEMANAGER_ERR_MAX_PLAYER_CAPACITY_TOO_LARGE = 15269892,
            GAMEMANAGER_ERR_INVALID_TEAM_CAPACITIES_VECTOR_SIZE = 16384004,
            GAMEMANAGER_ERR_DUPLICATE_TEAM_CAPACITY = 16449540,
            GAMEMANAGER_ERR_INVALID_TEAM_ID_IN_TEAM_CAPACITIES_VECTOR = 16515076,
            GAMEMANAGER_ERR_TEAM_NOT_ALLOWED = 16580612,
            GAMEMANAGER_ERR_TOTAL_TEAM_CAPACITY_INVALID = 16646148,
            GAMEMANAGER_ERR_TEAM_FULL = 16711684,
            GAMEMANAGER_ERR_TEAMS_DISABLED = 16777220,
            GAMEMANAGER_ERR_INVALID_TEAM_CAPACITY = 16842756,
            GAMEMANAGER_ERR_NO_DEDICATED_SERVER_FOUND = 19726340,
            GAMEMANAGER_ERR_DEDICATED_SERVER_ONLY_ACTION = 19791876,
            GAMEMANAGER_ERR_DEDICATED_SERVER_HOST_CANNOT_JOIN = 19857412,
            GAMEMANGER_ERR_MACHINE_ID_LIST_EMPTY = 19922948,
            GAMEMANAGER_ERR_DYNAMIC_GAME_CREATION_TIMED_OUT = 19988484,
            GAMEMANAGER_ERR_DYNAMIC_GAME_CREATION_FAILED_NO_CAPACITY = 20054020,
            GAMEMANAGER_ERR_DYNAMIC_DEDICATED_SERVER_MODE_CONFLICT = 20119556,
            GAMEBROWSER_ERR_INVALID_CRITERIA = 26279940,
            GAMEBROWSER_ERR_INVALID_CAPACITY = 26345476,
            GAMEBROWSER_ERR_INVALID_LIST_ID = 26411012,
            GAMEBROWSER_ERR_NOT_LIST_OWNER = 26476548,
            GAMEBROWSER_ERR_INVALID_LIST_CONFIG_NAME = 26542084,
            GAMEBROWSER_ERR_CANNOT_GET_USERSET = 26607620,
            GAMEMANAGER_ERR_GAME_CAPACITY_TOO_SMALL = 32899076,
            GAMEMANAGER_ERR_INVALID_ACTION_FOR_GROUP = 32964612,
            GAMEMANAGER_ERR_NOT_PLATFORM_HOST = 33030148,
            GAMEMANAGER_ERR_MIGRATION_NOT_SUPPORTED = 33095684,
            GAMEMANAGER_ERR_INVALID_NEWHOST = 33161220,
            GAMEMANAGER_ERR_USER_NOT_IN_ANY_GAME = 33226756,
            GAMEMANAGER_ERR_INVALID_PERSISTED_GAME_ID_OR_SECRET = 33292292,
            GAMEMANAGER_ERR_PERSISTED_GAME_ID_IN_USE = 33357828
        }
    }
}
